services:
  - type: web
    name: truck-rental
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run serve:ssr:Truck-Rental
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://truck-rental.onrender.com
